### ISSUE TITLE
What is the token expiration time ?

### ISSUE THREAD

**Issue by vitoo** [Cleanse/discord-php#8]
Hello,

Thank for this lib !

When doing email/password login, the token should expire in how much time ? To properly set the cache time.

Thanks

`$cachedToken = $discord->token();
`

**Comment by Cleanse** [comment]
Try setting an int with 300 as the value. Unsure if my lib even works anymore.

You can look at my buddies project https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Http/Http.php

**Comment by vitoo** [comment]
you mean 300 seconds ?

Dead project lol, but i already used it for bot

I dont know if it can handle email/password login

**Comment by Cleanse** [comment]
You should swap to one of the stable projects. https://discord.gg/discord-api

**Comment by vitoo** [comment]
The user token is in localstorage of browser when logged in discord :)
